apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-app
  name: grafana-service
spec:
  ports:
    - name: "3090"
      port: 3000
      targetPort: 3000
  selector:
    app: grafana-app
  type: LoadBalancer