apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-demo-app
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
        - name: grafana-demo-app
          image: grafana/grafana:11.3.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-config
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-app-secret
                  key: admin_user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-app-secret
                  key: admin_password
      restartPolicy: Always
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-configmap
            # 110100100 rw-r--r--
            defaultMode: 420
